/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SpecialtiesSlugRouteImport } from './routes/specialties.$slug'
import { Route as DoctorsIdRouteImport } from './routes/doctors.$id'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin/withdrawals'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminInfoPagesRouteImport } from './routes/admin/info-pages'
import { Route as AdminHomeSettingsRouteImport } from './routes/admin/home-settings'
import { Route as AdminFeesRouteImport } from './routes/admin/fees'
import { Route as AdminDoctorRequestsRouteImport } from './routes/admin/doctor-requests'
import { Route as AdminAppointmentsRouteImport } from './routes/admin/appointments'
import { Route as AdminAppointmentsIdRouteImport } from './routes/admin/appointments.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SpecialtiesSlugRoute = SpecialtiesSlugRouteImport.update({
  id: '/specialties/$slug',
  path: '/specialties/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsIdRoute = DoctorsIdRouteImport.update({
  id: '/doctors/$id',
  path: '/doctors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInfoPagesRoute = AdminInfoPagesRouteImport.update({
  id: '/info-pages',
  path: '/info-pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomeSettingsRoute = AdminHomeSettingsRouteImport.update({
  id: '/home-settings',
  path: '/home-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeesRoute = AdminFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDoctorRequestsRoute = AdminDoctorRequestsRouteImport.update({
  id: '/doctor-requests',
  path: '/doctor-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppointmentsIdRoute = AdminAppointmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAppointmentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/appointments': typeof AdminAppointmentsRouteWithChildren
  '/admin/doctor-requests': typeof AdminDoctorRequestsRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/home-settings': typeof AdminHomeSettingsRoute
  '/admin/info-pages': typeof AdminInfoPagesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/doctors/$id': typeof DoctorsIdRoute
  '/specialties/$slug': typeof SpecialtiesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/appointments/$id': typeof AdminAppointmentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/appointments': typeof AdminAppointmentsRouteWithChildren
  '/admin/doctor-requests': typeof AdminDoctorRequestsRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/home-settings': typeof AdminHomeSettingsRoute
  '/admin/info-pages': typeof AdminInfoPagesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/doctors/$id': typeof DoctorsIdRoute
  '/specialties/$slug': typeof SpecialtiesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/appointments/$id': typeof AdminAppointmentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/appointments': typeof AdminAppointmentsRouteWithChildren
  '/admin/doctor-requests': typeof AdminDoctorRequestsRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/home-settings': typeof AdminHomeSettingsRoute
  '/admin/info-pages': typeof AdminInfoPagesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/doctors/$id': typeof DoctorsIdRoute
  '/specialties/$slug': typeof SpecialtiesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/appointments/$id': typeof AdminAppointmentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/admin/appointments'
    | '/admin/doctor-requests'
    | '/admin/fees'
    | '/admin/home-settings'
    | '/admin/info-pages'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/doctors/$id'
    | '/specialties/$slug'
    | '/admin/'
    | '/admin/appointments/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin/appointments'
    | '/admin/doctor-requests'
    | '/admin/fees'
    | '/admin/home-settings'
    | '/admin/info-pages'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/doctors/$id'
    | '/specialties/$slug'
    | '/admin'
    | '/admin/appointments/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/admin/appointments'
    | '/admin/doctor-requests'
    | '/admin/fees'
    | '/admin/home-settings'
    | '/admin/info-pages'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/doctors/$id'
    | '/specialties/$slug'
    | '/admin/'
    | '/admin/appointments/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  DoctorsIdRoute: typeof DoctorsIdRoute
  SpecialtiesSlugRoute: typeof SpecialtiesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/specialties/$slug': {
      id: '/specialties/$slug'
      path: '/specialties/$slug'
      fullPath: '/specialties/$slug'
      preLoaderRoute: typeof SpecialtiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/$id': {
      id: '/doctors/$id'
      path: '/doctors/$id'
      fullPath: '/doctors/$id'
      preLoaderRoute: typeof DoctorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/info-pages': {
      id: '/admin/info-pages'
      path: '/info-pages'
      fullPath: '/admin/info-pages'
      preLoaderRoute: typeof AdminInfoPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/home-settings': {
      id: '/admin/home-settings'
      path: '/home-settings'
      fullPath: '/admin/home-settings'
      preLoaderRoute: typeof AdminHomeSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fees': {
      id: '/admin/fees'
      path: '/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AdminFeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/doctor-requests': {
      id: '/admin/doctor-requests'
      path: '/doctor-requests'
      fullPath: '/admin/doctor-requests'
      preLoaderRoute: typeof AdminDoctorRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appointments/$id': {
      id: '/admin/appointments/$id'
      path: '/$id'
      fullPath: '/admin/appointments/$id'
      preLoaderRoute: typeof AdminAppointmentsIdRouteImport
      parentRoute: typeof AdminAppointmentsRoute
    }
  }
}

interface AdminAppointmentsRouteChildren {
  AdminAppointmentsIdRoute: typeof AdminAppointmentsIdRoute
}

const AdminAppointmentsRouteChildren: AdminAppointmentsRouteChildren = {
  AdminAppointmentsIdRoute: AdminAppointmentsIdRoute,
}

const AdminAppointmentsRouteWithChildren =
  AdminAppointmentsRoute._addFileChildren(AdminAppointmentsRouteChildren)

interface AdminRouteChildren {
  AdminAppointmentsRoute: typeof AdminAppointmentsRouteWithChildren
  AdminDoctorRequestsRoute: typeof AdminDoctorRequestsRoute
  AdminFeesRoute: typeof AdminFeesRoute
  AdminHomeSettingsRoute: typeof AdminHomeSettingsRoute
  AdminInfoPagesRoute: typeof AdminInfoPagesRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAppointmentsRoute: AdminAppointmentsRouteWithChildren,
  AdminDoctorRequestsRoute: AdminDoctorRequestsRoute,
  AdminFeesRoute: AdminFeesRoute,
  AdminHomeSettingsRoute: AdminHomeSettingsRoute,
  AdminInfoPagesRoute: AdminInfoPagesRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  DoctorsIdRoute: DoctorsIdRoute,
  SpecialtiesSlugRoute: SpecialtiesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
